title: jo-kim blog
description: jo-kim의 기술 블로그
theme: just-the-docs

url: https://kim-jinoh.github.io/blog

aux_links:
  Template Repository: https://github.com/kim-jinoh/blog

logo: /assets/images/software-engineer-logo.png
favicon_ico: /assets/images/software-engineer-logo.png

ga_tracking: G-9YGJH1NW48

defaults:
  - scope:
      path: ""
    values:
      layout: home